# Site settings
title: Ann Arbor Ruby Brigade
email: support@a2rb.org
description: > # this means to ignore newlines until "baseurl:"
  Ann Arbor Ruby Brigade is a Ruby language user group for beginners and experts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://a2rb.org" # the base hostname & protocol for your site
twitter_username: a2rb
github_username:  a2rb

# Build settings
markdown: kramdown
